make ghc-doc-index arch since haddock disabled on i686
BuildError: The following noarch package built differently on different architectures: ghc-doc-index-9.2.5-125.fc38.noarch.rpm
rpmdiff output was:
added       /usr/share/doc/ghc/html/libraries/doc-index-124.html
added       /usr/share/doc/ghc/html/libraries/doc-index-126.html
added       /usr/share/doc/ghc/html/libraries/doc-index-33.html
:
: