ghc-wrapper-libffi-include.patch for "missing libffi.h" when compiling prof on secondary archs
eg on armv7:

[ 1 of 21] Compiling Data.Functor.Product ( Data/Functor/Product.hs, dist/build/Data/Functor/Product.p_o )

/tmp/ghc1692_0/ghc1692_0.c:4:17:
     fatal error: ffi.h: No such file or directory